### ISSUE TITLE
Dudas

### ISSUE THREAD

**Issue by Pelirrojo** [shylvis/PracticaFinal#1]
Hola,

He intentado arrancar el dashboard y me arroja el siguiente error:
````javascript
user@MacBook PracticaFinal (master) $ node index.js
Puerto 3000!
Database is connected ... nn
/Users/username/Desktop/PracticaFinal/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

Error: ER_WRONG_FIELD_WITH_GROUP: Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'practicafinal.b.costo' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
    at Query.Sequence._packetToError (/Users/username/Desktop/PracticaFinal/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/username/Desktop/PracticaFinal/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/username/Desktop/PracticaFinal/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/username/Desktop/PracticaFinal/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/username/Desktop/PracticaFinal/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/username/Desktop/PracticaFinal/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Protocol._enqueue (/Users/username/Desktop/PracticaFinal/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/Users/username/Desktop/PracticaFinal/node_modules/mysql/lib/Connection.js:208:25)
    at app.get (/Users/username/Desktop/PracticaFinal/index.js:29:14)
    at Layer.handle [as handle_request] (/Users/username/Desktop/PracticaFinal/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/username/Desktop/PracticaFinal/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/username/Desktop/PracticaFinal/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/username/Desktop/PracticaFinal/node_modules/express/lib/router/layer.js:95:5)
    at /Users/username/Desktop/PracticaFinal/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/username/Desktop/PracticaFinal/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/username/Desktop/PracticaFinal/node_modules/express/lib/router/index.js:275:10)
````

Si pudieras indicar la versión de MySQL, así como revisar la muestra de datos te estaría muy agradecido. También si tienes otra idea del origen del error es bienvenida.

Muchas gracias de antemano.
Un cordial saludo,
Manuel

**Comment by shylvis** [comment]
El error se origina por la versión de MySql Instalada, a partir de la versión 5.7.5 ocurre dicho inconveniente.
Debido a la inclusión de ONLY_FULL_GROUP_BY.

**Instalar mysql:**
**Opción 1:** Descargar gratis apache [XAMP](https://www.apachefriends.org/es/index.html) cualquiera de estas versiones 5.6.36, 7.0.30, 7.1.17 & 7.2.5
Levantar los servicios en el panel administrador MySql.
**Opción 2:** Instalar Mysql Versión anterior a 5.7:
-- MySQL dump 10.13  Distrib 5.6.17
-- Server version 5.5-10.1.30-MariaDB

**Opción 3:** Instalar Mysql Versión posterior a 5.6:
--Deshabilitar ONLY_FULL_GROUP_BY puede desactivarlo quitándolo de su sql_mode. 

`SET @@GLOBAL.sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'`

No es necesario reiniciar, pero sí una reconexión

-- Cambio permanente:
Si desea deshabilitarlo permanentemente, agregue / edite lo siguiente en su archivo my.cnf:
`sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
`
Para este cambio, se requiere un reinicio del servicio:
`$ mysql service restart`

Mas información: https://dev.mysql.com/doc/refman/8.0/en/group-by-handling.html

**Comment by Pelirrojo** [comment]
Esto lo resuelve!
Muchas gracias!
